language: php

dist:
  - trusty
php:
  - 5.5.9
  - 5.6
  - 7.0

before_script:
  - composer install --prefer-source --no-interaction --dev
  - touch ./database/database.sqlite
  - php artisan migrate

env:
  global:
    - APP_ENV=staging
    - APP_DEBUG=true
    - APP_KEY=xxxx
    - DB_CONNECTION=sqlite
    - CACHE_DRIVER=file
    - SESSION_DRIVER=file
    - QUEUE_DRIVER=sync

script: phpunit --coverage-text